// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCztTl5qlcFkbalW7nhHWr8H71ijpjV7RA',
    appId: '1:873095408162:web:b32386bb1b7c7cadf7787b',
    messagingSenderId: '873095408162',
    projectId: 'ari-yapi-takip',
    authDomain: 'ari-yapi-takip.firebaseapp.com',
    storageBucket: 'ari-yapi-takip.firebasestorage.app',
    measurementId: 'G-W6N6PV7J92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlCPxJpUSHp0hjwxQqspSihT3dTjJ-Uyk',
    appId: '1:873095408162:android:d777c44c5206467af7787b',
    messagingSenderId: '873095408162',
    projectId: 'ari-yapi-takip',
    storageBucket: 'ari-yapi-takip.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEQPeOdsaoN-yuo4O1CTgIh9JTYvi6-dQ',
    appId: '1:873095408162:ios:61fab7e7550086cdf7787b',
    messagingSenderId: '873095408162',
    projectId: 'ari-yapi-takip',
    storageBucket: 'ari-yapi-takip.firebasestorage.app',
    iosBundleId: 'com.example.ariYapiTakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEQPeOdsaoN-yuo4O1CTgIh9JTYvi6-dQ',
    appId: '1:873095408162:ios:61fab7e7550086cdf7787b',
    messagingSenderId: '873095408162',
    projectId: 'ari-yapi-takip',
    storageBucket: 'ari-yapi-takip.firebasestorage.app',
    iosBundleId: 'com.example.ariYapiTakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCztTl5qlcFkbalW7nhHWr8H71ijpjV7RA',
    appId: '1:873095408162:web:dfe8bfaa3de777f6f7787b',
    messagingSenderId: '873095408162',
    projectId: 'ari-yapi-takip',
    authDomain: 'ari-yapi-takip.firebaseapp.com',
    storageBucket: 'ari-yapi-takip.firebasestorage.app',
    measurementId: 'G-XVFQ5C96TP',
  );
}
